DROP SEQUENCE trg_saved_report_dates_seq;

CREATE SEQUENCE trg_saved_report_dates_seq;

DROP TABLE TRG_SAVED_REPORT_DATES;

CREATE TABLE TRG_SAVED_REPORT_DATES
  (
  REPORTING_DATE_ID NUMBER (5) PRIMARY KEY,
  END_DATE DATE NOT NULL
 );
 
DELETE TRG_SAVED_REPORT_DATES;

INSERT INTO TRG_SAVED_REPORT_DATES (REPORTING_DATE_ID,END_DATE)
VALUES (trg_reporting_dates_seq.NEXTVAL,TO_DATE('04/23/2004','MM/DD/YYYY'));

COMMIT;
