CREATE OR REPLACE SEQUENCE niku.trg_reporting_dates_seq;

CREATE OR REPLACE TABLE niku.TRG_REPORTING_DATES
  (
  REPORTING_DATE_ID NUMBER (5) PRIMARY KEY,
  BEGIN_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  PERIOD VARCHAR2 (5) NOT NULL
 );
 
COMMIT;
